apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - network-policies.yaml
  - postgres.yaml
  - garage.yaml
  - kafka.yaml
  - debezium.yaml
  - polaris.yaml
  - polaris-setup.yaml
  - trino.yaml
  - spark.yaml
  - airflow.yaml
  - observability.yaml
